[tool.poetry]
name = "jax_pep503"
version = "0.1.0"
description = "PEP 503 compliant repository for Jax"
authors = ["jorenham <jhammudoglu@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.72.0"
uvicorn = "^0.17.0"
Jinja2 = "^3.0.3"
httpx = "^0.21.3"
yarl = "^1.7.2"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
build = 'jax_pep503.build:build_index'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
