name: Rebuild

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0

      - name: Poetry install
        run: poetry install

      - name: Build html
        run: poetry run build

      - name: Publish
        uses: EndBug/add-and-commit@v7
        with:
          add: 'docs'
          branch: master
          message: 'auto daily html build'
